### ISSUE TITLE
Calculation error

### ISSUE THREAD

**Issue by kuailehaha** [davisgcii/optimization-by-prompting#1]
![aa5da0af447e0fad97d430286912e0e](https://github.com/davisgcii/optimization-by-prompting/assets/56251725/4ed2b36f-9b91-426a-9176-aad7dc0cd8b1)

**Comment by davisgcii** [comment]
Good catch. After double checking my distance calculation function over and over, I discovered that they aren't actually following their own description:

"The trace should traverse all points exactly once"

Instead, they're traversing each point once and then adding the distance to get back to the initial point.

**Comment by davisgcii** [comment]
Fixed in main.
